name: CI

on:
  push:
    branches:
    - master
    tags:
    - !refs/tags/*
  pull_request:

jobs:
  test:
    name: foo
    steps:
    - uses: actions/checkout@v1
    - name: foo
      run: echo hello
