name: Ruby 2

on:
  push:
    branches:
      - master
      - develop
  pull_request: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest

    name: Yo
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Everywhere"
      run: echo hi
    - name: "Linux"
      run: |
        echo hello
        echo world
      if: matrix.os != 'macOS-latest'
