on:
  push:
    branches:
    - master
  repository_dispatch:

jobs:
  test:
    name: Yo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print Environment Version
      run: echo $GITHUB_WORKSPACE
