name: CI

on:
  push:
    branches:
    - master
    tags:
    - '!*'
  pull_request:
    paths:
    - '*'

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: foo
      run: echo hello
